### ISSUE TITLE
iOS Firefox search not working

### ISSUE THREAD

**Issue by mobilutz** [trovu/trovu#102]
When adding Trovu to Firefox on iOS, I do not get redirected to the result at all. I only see the search field filled with what I searched for.

I will try ti use debug to see what this prints and will add the output here as well.

![image](https://user-images.githubusercontent.com/491877/210179166-3fe05df4-8e6b-40f9-9683-af6167cb0541.png)

PS: debug does not help, as the search is not being done at all.

**Comment by georgjaehnig** [comment]
Thanks for reporting! Hmm, this looks to me as if in the template URL, the `process/` part is missing. Can you check this template URL and if it really starts with

    https://trovu.net/process/?#...

**Comment by georgjaehnig** [comment]
And thanks for the screenshot, it reminds me why we badly need #60 and #90. :)

**Comment by georgjaehnig** [comment]
Lacking an iOS device, I could now only try with Firefox for Android – and it #worksforme. Here's a screenshot of my setting:

![image](https://user-images.githubusercontent.com/1092628/210268130-ef2f2255-64c1-44b0-8169-1140600b3785.png)

**Comment by mobilutz** [comment]
🤦🏻 I really did forget the `/process` part. I guess I was not looking too well here:
https://github.com/trovu/trovu.github.io/wiki/Use-Trovu-on-your-device#other

With this, it is working!

**Comment by georgjaehnig** [comment]
Good to know, I made the description more clear.

BTW, can you check if the process on Firefox for iOS is the same as [for Firefox on Android](https://github.com/trovu/trovu.github.io/wiki/Use-Trovu-on-your-device#firefox-for-android)? If yes, I could add this info.
