### ISSUE TITLE
Add "Add to browser" button

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#11]
will add Trovu incl. all current params as (default) search engine in browser.

**Comment by texttheater** [comment]
+1. Annoyingly, Firefox no longer has any UI to define custom search engines with URL templates, so this one’s important.

**Comment by georgjaehnig** [comment]
I do agree. Just wanted to add this as I thought it's a quick fix.

Then I found out that the Javascript function that I can call with [window.external.AddSearchProvider(engineURL);](https://developer.mozilla.org/en-US/docs/Web/API/Window/sidebar/Adding_search_engines_from_Web_pages) needs to point to an OpenSearch XML definition file, like [this one](https://www.findfind.it//opensearch/n/de.deu).

Now, the problem is that trovu-web is currently a Frontend-only project. Only HTML and client-side Javascript. However, the OpenSearch XML definition file needs to contain the namespace names. 

So the problem is: I'd need to create the XML file dynamically, at least the namespace definition in there. And I have no idea how I could do that.

I thought about pre-generating XML files, but that would be a number of `countLanguages * countNamespaces`, and I'd still have no custom namespaces.

Or I need to start having some server-side code.

Feel free to comment if you have any ideas.

**Comment by texttheater** [comment]
Does [window.external.AddSearchProvider(engineURL)](https://developer.mozilla.org/en-US/docs/Web/API/Window/sidebar/Adding_search_engines_from_Web_pages) accept a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)? That should make it possible to generate it dynamically on the client side.

**Comment by georgjaehnig** [comment]
This looked promising! Tried it out, failed, and then I found this: https://stackoverflow.com/questions/47578735/how-to-call-browser-function-with-url-uri-local-to-the-client

> Update: Firefox is indeed enforcing the URL to be of HTTP, HTTPS or FTP:

:(

**Comment by texttheater** [comment]
Damn! Perhaps one could set up one central service with no other purpose than to generate the required OpenSearch XML (and possibly also provide UI to add it). However, I am now almost expecting Firefox to foil this too by requiring the search engine URL be on the same domain as the OpenSearch XML...

**Comment by georgjaehnig** [comment]
Did it now, with using some server-side PHP. Check https://trovu.net/
