### ISSUE TITLE
Do not "store" trovu URL in browser-history

### ISSUE THREAD

**Issue by mobilutz** [trovu/trovu#112]
Current, the query-URL is being stored in the browser history as one entry. This makes is strange when using `back` button on the browser.

There are ways to do this, but I don't have a documentation for them right now :|

**Comment by georgjaehnig** [comment]
Hi! Exactly for this problem, [rewriteBrowserHistory](https://github.com/trovu/trovu-web/blob/master/src/js/modules/CallHandler.js#L158-L168) was implemented. It should cause that when hitting the Back button, the `process/` page is omitted.

I remember that you use Firefox and just checked if it works there – and it doesn't! Thanks for reporting.

**Comment by georgjaehnig** [comment]
Current status: I see on my Firefox that the URL in fact *does* get rewritten to the homepage `trovu.net/index.html` – but Firefox still delivers the (cached?) content from `trovu.net/process`.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/1092628/211582699-c10a9e23-1453-4986-92ab-82421585921f.png">

Can you confirm if it's the same on your side?

So there seems to be some aggressive caching at play. But only on Firefox..

**Comment by mobilutz** [comment]
Thanks for the quick fix. With the change you did, the history is empty again!
