### ISSUE TITLE
Unify (error) logging

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#147]
Log and display in a unified way, e.g. with https://github.com/winstonjs/winston

**Comment by georgjaehnig** [comment]
Hi @caeschfloh, I noticed you made [this edit to your local trovu-data-user](https://github.com/caeschfloh/trovu-data-user/commit/1e3550123a57f71e549fd174fff840c086f576fe), after having added a new key with the wrong syntax previously. Did the new error logging helped you to find this error, and/or is there room for improvement?

**Comment by caeschfloh** [comment]
helped. thx.Von: Georg Jähnig ***@***.***>Gesendet: Freitag, August 11, 2023 5:20:49 AMAn: trovu/trovu-web ***@***.***>Cc: caeschfloh ***@***.***>; Mention ***@***.***>Betreff: Re: [trovu/trovu-web] Unify (error) logging (Issue #147)
Hi @caeschfloh, I noticed you made this edit to your local trovu-data-user, after having added a new key with the wrong syntax previously. Did the error logging helped you to find this error, and/or is there room for improvement?
