### ISSUE TITLE
Allow different dictionaries for each direction

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#155]
Currently, dictionary are created shortcuts are created semi-automatically via [tools.js](https://github.com/trovu/trovu-web/blob/master/src/js/tools.js#L285) and [dictionaries.yml](https://github.com/trovu/trovu-web/blob/master/src/yml/dictionaries.yml).

The tooling code assumes for each language pair, e.g. `cs-de` and `de-cs` only one shortcut (the latter `include:`'ing the former).

But for some dictionaries, we want to have separate URLs, e.g. for `dict.com`:

- `cs-de:` https://dict.com/czech-german/strom (shows Czech declination but not German one)
- `de-cs:` https://dict.com/german-czech/baum (shows German declination but not Czech one)

This should be allowed by the tooling code.

**Comment by andrej-repisky** [comment]
I think it's unnecessary to change Tooling code. We can just use https://dict.com/german-czech/baum for both directions. Czechs are learning German much more often than the other way round :-)

**Comment by georgjaehnig** [comment]
Yeah but I reapply the tooling code on every new added dict.

But feel free to [fix it now manually](https://github.com/trovu/trovu-data/blob/master/shortcuts/dcm.yml#L2273), I'll fix the tooling once I have more time.

**Comment by georgjaehnig** [comment]
Done with #370.
