### ISSUE TITLE
Language specifc sites stopped working

### ISSUE THREAD

**Issue by ospalh** [trovu/trovu#156]
Today, using my personal settings (ospalh/trovu-data-user), language specific sites stopped working.
E.g. en.w DCF77 goes to the German Wikipedia site, instead of the English one.
I havn’t tucht my data-user repo in a while.

**Comment by georgjaehnig** [comment]
Thanks for reporting. Can confirm. Working on it.

**Comment by georgjaehnig** [comment]
Should be fixed now. If not, please reopen.
