### ISSUE TITLE
Wrong instructions for Firefox

### ISSUE THREAD

**Issue by andrej-repisky** [trovu/trovu#157]
The instructions on https://github.com/trovu/trovu.github.io/wiki/Use-Trovu-on-your-device#firefox seem to be outdated, because there is no "Add Trovu" in the context menu anymore.

The instructions are at the same time urgently needed, because even after 15 minutes I didn't figure it out how to do it.

I'm on Firefox 116.0 under Ubuntu 64-bit.

**Comment by georgjaehnig** [comment]
We could resolve this with chat communication. Description is correct, but was [improved with a screenshot](https://github.com/trovu/trovu.github.io/wiki/Use-Trovu-on-your-device).
