### ISSUE TITLE
Remember language & country setting

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#189]
Currently, if a non-logged user changed the current language or country, leaves Trovu and comes back later, the change is gone. Instead, these settings are picked by the algorithms as if the user would have come new to the site.

This should be different: The change of current namespaces shall be remembered.

Could be implemented by cookie. Problem: Don't create the need for a cookie banner

(imported from https://github.com/georgjaehnig/serchilo-drupal/issues/146)

**Comment by stefanschramm** [comment]
You can simply put a `[ ] Store settings in cookie`-checkbox in the language/namespace settings dialog; not enabled by default

**Comment by georgjaehnig** [comment]
Decided to not fix. If someone really uses Trovu regularly, they can either [add it to their browser](https://trovu.net/docs/users/integration/), or create a bookmark with the URL params containing language and country.
