### ISSUE TITLE
Welt.de öffnet Lingea

### ISSUE THREAD

**Issue by andrej-repisky** [trovu/trovu#200]
Schritte

- Meinen angepassten Trovu öffnen: https://trovu.net/index.html#github=andrej-repisky
- Suchbegriff tippen, bspw "welt.de umwelt"
- öffnet sich https://slovniky.lingea.cz/nemecko-cesky/umwelt

Soll:
welt.de soll kein besonderer Befehl sein.

**Comment by georgjaehnig** [comment]
Danke. Das liegt daran, dass `welt` als extra namespace interpretiert wird, in dem dann nach dem Keyword `de` gesucht wird. Das finde bei dir dann das Deutsch-Tschechisch-Wörterbuch.

Müsste im Code so gelöst werden, dass extra-Namespaces nur sein dürfen:

- ist als Namespace in aktueller `env` geladen, oder
- hat 2 Buchstaben (für eventuellen Sprache-Namespace), oder
- hat einen Punkt und 2 Buchstaben (für eventuellen Landes-Namespace).
