### ISSUE TITLE
LaTeX entfernen

### ISSUE THREAD

**Issue by andrej-repisky** [trovu/trovu#223]
Der Befehl "Latex" scheint nichts vernünftiges zu tun und stört mich sehr.
Meine Anfrage "latex horizontal space" öffnet Google Suche mit dem Suchtext "horizontal space site:www.giss.nasa.gov inurl:tools/latex"

**Comment by georgjaehnig** [comment]
OK, hab es entfernt in 934980ba2b11b103741bf8b1533a76696b37c867. 

Fände aber sonst eine Latex-Doku/Referenz ganz praktisch, dann vllt. unter `ltx 1`. Kennst Du eine empfehlenswerte?

**Comment by andrej-repisky** [comment]
Nein, keine Ahnung. Ja, `ltx` ist besser.
