### ISSUE TITLE
Allow passing full URL to config

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#236]
For allowing "private" shortcut files, it will become necessary to allow a fully specified url.

Example:

https://trovu.net/?#process&uri=https://mynextcloudserver.org/hash42424242/download&query=%s

related to #235 

Files could be for example

- pastebin or dpaste (raw output: dpasteurl```.txt```)
- nextcloud textfiles (raw output: nextcloudurl```/download```)
- Etherpads (raw output:  padurl```/export/txt``` )

**Comment by georgjaehnig** [comment]
Instead of `url=`, we should rather name this `config=`, to be more specific, and as it will refer to `config.yml`.

**Comment by Wikinaut** [comment]
> Instead of `url=`, we should rather name this `config=`, to be more specific, and as it will refer to `config.yml`.

I think, this parameter is now ```configUrl=```, isn't it?

**Comment by Wikinaut** [comment]
works for me
thanks & applause

**Comment by georgjaehnig** [comment]
> I think, this parameter is now `configUrl=`, isn't it?

Yes, as it's more specific. 

[Docs are here](https://trovu.net/docs/users/advanced/).

**Comment by Wikinaut** [comment]
> > I think, this parameter is now `configUrl=`, isn't it?
> 
> Yes, as it's more specific.
> 
> [Docs are here](https://trovu.net/docs/users/advanced/).

Ich wollte nur anregen, dass es oben schon in Deinem Post änderst (= aktualisierst).
