### ISSUE TITLE
For non-unique, for example for duplicate shortcuts, show an exact error message listing all these non-unique entries

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#238]
Warning: Parse error in https://raw.githubusercontent.com/$user/trovu-data-user/master/shortcuts.yml?1111: duplicated mapping key ($line)

There should be an exact error message, which keys are non unique, i.e. listen the two (or more) duplicate entries.

**Comment by georgjaehnig** [comment]
I've just reproduced that with my user shortcuts. The error message says:
```
Warning: Parse error in https://raw.githubusercontent.com/georgjaehnig/trovu-data-user/master/shortcuts.yml?7586abb: duplicated mapping key (41:1)
...
 41 | zz 1: https://www.google.de/sea ...
------^
```
So it shows you exactly the key that is not unique. Isn't that what you are asking for?
