### ISSUE TITLE
For parsing errors, when coming from the browser search bar, show the error message and wait for user confirmation until proceeding

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#239]
Warning: Parse error in ....: duplicated mapping key (92:1)

## Problem

For parsing errors, when coming from the browser search bar, the error message is flashing for  a second or so and there's no distinct way to to stop this.

I suggest to implement a confirmation button the user has to click to proceed processing.

related to #238

**Comment by georgjaehnig** [comment]
The error logging has 2 levels for this:

- `.error`: Here, the execution stops
- `.warning`: Here, it shows and continues.

However,  on the homepage, if you are not sending a query, the error message does show.

So this error message, coming from a YAML parsing error, will be kept shown on the homepage.

I was deliberately choosing which error level to apply when. For some time, I had `.error` on YAML parsing errors. But I found them too intrusive. They would also stop a users' search with a site shortcut – which is not related to their user shortcuts. So I decided to apply here a `.warning`.
