### ISSUE TITLE
[Proposal] Allow a list of aliases to an existing shortcut

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#240]
1. I wish to add an alias to an existing shortcut.

Let's say, I want to add "goooo" as shortcut to an existing shortcut "g". How can this be done?
(Should be added to the FAQ.)

2. I wish to add an alias to an existing internal action (example: I wish to have "refresh" as an alias to "reload"). How can this be done?
(Should be also added to the FAQ.)

**Comment by Wikinaut** [comment]
I changed the title from ```Support request``` to ```proposal```.

**Comment by Wikinaut** [comment]
### Example

### proposal: add a further keyword "aliases" and a space or comma-separated list of aliases

```
gh 0:
        aliases: ghub github gith
        url: https://github.com/
        title: GitHub
        tags:
          - software
``` 


By the way: that's similar to what I coded in QuickSource. There I used also regular expressions for defining the shortcuts (example: ```gith*```), because the shortcuts were stored in a MySQL table and MySQL even allowed to _have_ RegExp in the keys!

**Comment by Wikinaut** [comment]
An alternative solution would be to have a simple new syntax (one line entry) where a list of aliases are simply pointing to another existing shortcut

"aliasing" ghub github gith "to" gh:

```
ghub github gith alias: gh
```
or
```
ghub github gith gh:  gh
```



I leave it up to you how to implement. It allows users to define their own shortcut names for existing shortcuts.

**Comment by georgjaehnig** [comment]
This already works with [include](https://trovu.net/docs/shortcuts/include/).

**Comment by georgjaehnig** [comment]
So closing this issue for now – feel free to reopen if `include:` is not doing the trick for you.

**Comment by georgjaehnig** [comment]
It might be a good idea for a [blog](https://trovu.net/blog/) article "How to created keyword aliases with Include" though..

**Comment by Wikinaut** [comment]
Sorry, I don't understand, asking again:

> How can I add "gith ghub github" as (three) aliases to "gh"?

Please can you add these concrete alias examples?

I can understand, that the present ```include:```offers a variety of more possiblities, but it looks to be overkill and very complicated to me where a simple "alias" would better suit.

**Comment by Wikinaut** [comment]
remark: I have no permission to reopen this issue, would like to do so.

**Comment by georgjaehnig** [comment]
> Please can you add these concrete alias examples?

OK, so there already exists in `o`:
```yaml
github 1:
  url: https://github.com/search?q=<query>
  title: GitHub
  tags:
  - programming
  examples:
  - arguments: php
    description: Search for "php"
```
Now, if you want to have 2 personal aliases, you define in your user namespace:
```yaml
gh 1:
  include:
    key: github 1
    namespace: o
ghub 1:
  include:
    key: github 1
    namespace: o
```

**Comment by Wikinaut** [comment]
This is my personal view, respectfully stated:
These are quite a lot of lines for the simple thing of aliasing.

Moreover, it also renders the shortcut list difficult to read, don't you think?

**Comment by georgjaehnig** [comment]
Yes, it needs more lines. That's a disadvantage.

Advantages are:

- You are automatically stopped from setting an alias that is already another alias or a keyword
- You can not only alias a shortcut, but also tweak it a little bit.
- It uses existing functionality, e.g. having the aliases in the suggestions works out of the box.

**Comment by Wikinaut** [comment]
I really have to lookup any single shortcut to which I want to give an alias before I can edit an alias? Uh, this is a lot of work.

**Comment by georgjaehnig** [comment]
Wouldn't you need to do that with your solution as well?

**Comment by Wikinaut** [comment]
No, because I used an certain shortcut for a long time, I trust them. I simply want to have a shorter name: an alias.

**Comment by Wikinaut** [comment]
could be a single line as mentioned:

x y z aliases: a

**Comment by georgjaehnig** [comment]
Yes, it could be shorter. 

But I am not convinced it is worth the effort.

**Comment by Wikinaut** [comment]
...well, when I remember my system, I asked my "clients" and they had plenty of other names for (example) "dutytravelrequestform". I decided to set up "dienstreiseantrag" and "dtrf" as aliases.

**Comment by Wikinaut** [comment]
this is just an (real) example.

**Comment by Wikinaut** [comment]
does not work for me (reloaded n times)

```
ctv 0:
  include:
    key: ccctv 0
    namespace: o
```
