### ISSUE TITLE
Faulty include crashes

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#265]
```
ctv 0:
  include: ccctv
pwgen 0:
  url: http://www.kessnux.de/anwendungen/passwort-generator.php
  title: Franks Passwortgenerator
```

**Comment by Wikinaut** [comment]
In other words, the parsing is so difficile, that any of my changes crashed trovu in the last days because of (my) entry errors.
I suggest to rework the parser, but do not have any idea how this could happen.

**Comment by georgjaehnig** [comment]
Can reproduce. Hanging up, without any error message is definitely not acceptable. Will take care of this.
