### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by texttheater** [trovu/trovu#28]
Because Trovu uses client-side redirects rather than server-side redirects like Serchilo, the redirecting page becomes part of the browser history. As a result, the back button does not work as expected: it takes you back to the redirecting page, and that just redirects you forward again (tested with Firefox 66.0; workaround: double-click on the back button). AFAIK, this should be possible to fix by rewriting the history (viz., removing the redirecting page from it).

**Comment by georgjaehnig** [comment]
Very good suggestion. Will be fixed.
