### ISSUE TITLE
[Suggestion for improvement] make shortcut type "0" (zero arguments) default (no reason to throw an error)

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#281]
I often add short shortcuts type 0 and forget to add the "0" argument in my shortcut data set, resulting in 

```Incorrect key "$shortcut" in namespace $namespace: Must have form "KEYWORD ARGUMENTCOUNT"```

I cannot find any reason why "zero arguments" can't be the default.
That's why I propose: missing "0" means no arguments.

**Comment by georgjaehnig** [comment]
Hi, thanks for the suggestion. I don't think though it's a good idea: It would add more magic that would be to be documented. Also I observed users adding a 1+ arg shortcut and forgetting the `1` in the key. Those users might get no error message, or a more misleading one.

**Comment by Wikinaut** [comment]
uh, time for a fork.... ;-)

**Comment by Wikinaut** [comment]
by the way, while adding almost any shortcut since migration to trovu, I made at least one mistake; this is why I wish to relax the strict conditions for shortcuts a litte bit, make them more relaxed and perhaps self-healing.

this is my personal wish; I can understand your different views.

**Comment by georgjaehnig** [comment]
> uh, time for a fork.... ;-)

Yes. The perks of free software!
