### ISSUE TITLE
e is undefined

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#282]
On Firefox 121.0.1 (64-bit), MacOS Sonoma, we have this bug:

![image](https://github.com/trovu/trovu/assets/1092628/039e354b-60c2-4b91-89c5-278c994eb62a)

![image](https://github.com/trovu/trovu/assets/1092628/73ee2be8-3195-48b9-92da-8f3750ef8835)

**Comment by georgjaehnig** [comment]
This is puzzling because the code there is this:

```js
  displaySettings() {
    // Set settings fields in navbar.
    const language = countriesList.languages[this.env.language];
    document.querySelector('.navbar .language').innerText = this.env.language;
    document.querySelector('.navbar .language').title = language.name;

    const country = countriesList.countries[this.env.country.toUpperCase()];
    document.querySelector('.navbar .country').innerText = country.emoji;
    document.querySelector('.navbar .country').title = country.name;

    // Set settings fields in settings modal.
    document.querySelector('#languageSetting').value = this.env.language;
    document.querySelector('#countrySetting').value = this.env.country;

    // Show and hide settings tabs depending on Github setting.
    if (this.env.github) {
      document.querySelector('.using-advanced').classList.remove('d-none');
      document.querySelector('.using-basic').classList.add('d-none');
    } else {
      document.querySelector('.using-basic').classList.remove('d-none');
      document.querySelector('.using-advanced').classList.add('d-none');
    }
  }
```

with line 33 being

```js
    document.querySelector('.navbar .language').title = language.name;
```

**Comment by stefanschramm** [comment]
It can be reproduced like this - browser doesn't matter:
`https://trovu.net/process/?#query=asdasd+asd+asd&country=DoesNotExist&language=DoesNotExist`

Edit: or directly: `https://trovu.net/index.html#country=DoesNotExist&language=DoesNotExist&query=asdasd+asd+asd&status=not_found`

You should implement handling for cases when the specified language is not known.

**Comment by georgjaehnig** [comment]
Error keeps appearing:

![image](https://github.com/trovu/trovu/assets/1092628/ccb2830a-b25f-443b-ab09-0af0ca744f29)

Also interesting:

![image](https://github.com/trovu/trovu/assets/1092628/294327cc-0186-47d0-9beb-58213827ba2a)
