### ISSUE TITLE
[Suggestion for improvement] Store additional personal shortcut/s in browser's local storage until later sync with user's repository

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#289]
### Status

Currently, there appears to be no possibility to quickly add new shortcuts "locally".
With "locally" I mean in the current browser session and without invoking a non-trovu-action like edit of website or upload to nextcloud.

### Suggestion

* Add a new trovu-action (process) **_add_** which enables users to store new additional personal shortcut/s in their browser's ```local storage```.
* Enable a further new action to **_synchronize (sync)_** later, when suitable, the new shortcuts with the user's own main shortcut repository. Basically, this is an upload or store or automatic or manual git commit action.
* Allow this **_sync_** manually or also automatically - after a grace period (hours, day)

**Comment by georgjaehnig** [comment]
What exactly would be the use case? Something like: The user is on its way and can't edit their `trovu-data-user` repo? When does this happen? (Please illustrate.)

**Comment by Wikinaut** [comment]
Use case 1:

* User uses their account on several devices, i.a. a smartphone. 
* For security reasons, only one single other device - not the mentioned smartphone - has edit/admin rights to the repo resource (github; server with ssh key or the like etc.).
* Thus, when the user is mobile, there's no possibility to actively add new shortcuts to the repo.
* In that way the described functions act basically as an in-place memo (shortcut note book) and active trovu service with the newly added shortcuts on that device
* → until the user has possibility to synchronize with the authoritative repo.

**Comment by georgjaehnig** [comment]
OK, for me that's a very, very specific use-case. An alternative would be to put the user-repo on something editable (which, if I remember correctly, was one of the reasons we implemented #235).

Or simply one could put the new shortcut data in their notes until they're home.

Writing all this new code for a LocalStorage approach (and maintaining it) doesn't seem to me useful for this usecase.

**Comment by Wikinaut** [comment]
My proposal aimed to _avoid the usage or installation of an extra tool;_ in that way, it would be more handy to store new shortcuts directly via trovu in the local browser storage for later synchronization with the main repository, as explained.

**Comment by Wikinaut** [comment]
I suggest to keep that issue open until I come with a pull-request with solution.

**Comment by georgjaehnig** [comment]
It's not only about implementing but also about maintaining, documenting etc. I won't merge code where are I don't see that the benefits outweigh the maintenance work.

Here's another idea how one can deal with the given use case. Define 2 user namespaces:

```yaml
namespaces:
- github: my-github-editable-from-smartphone # Second user shortcuts
- o
- de
- .de
- github: .  # Main user shortcuts, heavily secured access
```
That way, you can always edit the second account, have the shortcuts immediately. And they will never override existing ones.
