### ISSUE TITLE
local installation: wrong country code (also: opensearch problem in /dist/public/opensearch/index.php)

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#332]
# local installation

In trovu/data I added `config.yml` (and `myshortcuts.yml`) as my personal shortcuts to the files in `trovu/data/shortcuts`
```namespaces:
- o
- de
- .de
- github: .
defaultKeyword: s
language: de
country: de
```
and then ` npm run build` (see also https://github.com/trovu/trovu/issues/330 ).

However, when starting, I got `https://mytrovuserver/#country=us&language=de` → with `us`.
(myshortcuts.yml are loaded as expected.)

What is going wrong, why is the `us` active?

**Comment by Wikinaut** [comment]
Added: I placed both the `config.yml` and `myshortcuts.yml` in `/trovu/data/shortcuts`. Perhaps the `config.yml` must be placed elsewhere? I do not know.

**Comment by Wikinaut** [comment]
I was wrong; the compilation of myshortcuts has failed, it appears so. (closing this issue for now)

**Comment by georgjaehnig** [comment]
In `data/shortcuts` you can only place shortcuts. Put `myshortcuts.yml` there and it should work, let me know.

I've also added a fix now that allows [Short notation](https://trovu.net/docs/shortcuts/#short-notation).

**Comment by Wikinaut** [comment]
Where do I then set the priority of namespaces and the default keyword (here: `s`)  as in my
```
- o
- de
- .de
- github: .
- myshortcuts
defaultKeyword: s
language: de
country: de
```

I do not understand, where this priority is to be defined.

**Comment by georgjaehnig** [comment]
> Where do I then set the priority of namespaces and the default keyword

With the usual ways [described here](https://trovu.net/docs/users/advanced/).

**Comment by Wikinaut** [comment]
It does not work; my shortcuts are not compiled.

**Comment by Wikinaut** [comment]
As proposed, I wanted to add my local shortcuts to the "o" shortcuts and then compile everything locally and to have a certain local shortcut as default for my local version , i. e. when I call https://mytrovu.net [without any additional query string]

Unluckily, this appears not to be possible at the moment.

Please let me kindly know, how I can achieve this behaviour.

**Comment by Wikinaut** [comment]
Without a github account or link to a page.

**Comment by georgjaehnig** [comment]
> I call https://mytrovu.net/ [without any additional query string]

So there's no way to do this without any additional query string.

If your use case is to run Trovu on your own server or localhost, I recommend:

- [Install according to the docs](https://trovu.net/docs/developers/)
- Put a `config.yml` into the built `/dist/public/` directory. [Include the shortcuts](https://trovu.net/docs/users/advanced/) in the `config.yml` (a feature that you [requested back then](https://github.com/trovu/trovu/issues/236)).
- Call Trovu with `https://mytrovu.net/#configUrl=%2Fconfig.yml`

This will get your local config file incl. your shortcuts.

**Comment by Wikinaut** [comment]
> > I call https://mytrovu.net/ [without any additional query string]
> 
> So there's no way to do this without any additional query string.
> 
> If your use case is to run Trovu on your own server or localhost, I recommend:
> 
>     * [Install according to the docs](https://trovu.net/docs/developers/)
> 
>     * Put a `config.yml` into the built `/dist/public/` directory. [Include the shortcuts](https://trovu.net/docs/users/advanced/) in the `config.yml` (a feature that you [requested back then](https://github.com/trovu/trovu/issues/236)).
> 
>     * Call Trovu with `https://mytrovu.net/#configUrl=%2Fconfig.yml`
> 
> 
> This will get your local config file incl. your shortcuts.

Ah, this is a little bit, what I expected what could work! I will try.

Perhaps (I am not sure) the `#configUrl=%2Fconfig.yml` could be put into the server config as default when `#configUrl` is missing or without a value.

**Comment by Wikinaut** [comment]
This appears to work (apache2) and adds the default `config.yml` when this is not present:

```
RewriteEngine on
RewriteCond %{REQUEST_URI} !index.html#configUrl
RewriteRule ^/$ /index.html#configUrl=/config.yml [NE,R=301]
```

I still suggest to add such a default behaviour in forthcoming trovu versions.

**Comment by Wikinaut** [comment]
When I want to add my local trovu as search engine to Firefox, I got the problem, that always only en-US is set up, which then results in not-found (active) shortcuts in the list. How could this problem be fixed?

![grafik](https://github.com/trovu/trovu/assets/1151915/92a5bbe3-1a98-4b8c-8c1a-b579366a922f)

**Comment by Wikinaut** [comment]
![grafik](https://github.com/trovu/trovu/assets/1151915/74f56df0-f3eb-4421-b2f8-1ae9be181533)

Problem: when want to add my local installation with the local configUrl as search engine, it always only adds `en-US` see (2),which results in having my local shortcuts not active. How could this be fixed?

The Web input (1) works fine with the local language de-DE.

**Comment by Wikinaut** [comment]
It appears to be a matter of the opensearch link which needs modification as well.

**Comment by Wikinaut** [comment]
Yep.

The problems stems from 
```
if (!empty($env['github'])) {
  $title .=  $env['github'];
}
else {
  // Set fallback values.
  $env['language'] = $env['language'] ?? 'de';
  $env['country']  = $env['country']  ?? 'de';
  $title .=  $env['language'] . '-' . strtoupper($env['country']);
}
```
in `/dist/public/opensearch/index.php`.

If local installation does not use the github configuration but a local configUrl., the country and language settings for opensearch need to follow the settings in configUrl. As a quick-and-dirty workaround I set the codes to `de` in `opensearch/index.php`.

The shortcuts are listed but not active.
The opensearch does not obey the configUrl - I have to file a new issue for this.
