### ISSUE TITLE
[After local shortcut compilation] reload fails

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#333]
I placed this `config.yml` into data/shortcuts
```namespaces:
- o
- de
- .de
- github: .
- shortcuts
defaultKeyword: s
language: de
country: de
```

and I placed my `shortcuts.yml` into the data/shortcuts.

`npm run build` works.

When starting my local trovu and `reload`, this hangs with (console):
![grafik](https://github.com/trovu/trovu/assets/1151915/d6873b9d-6762-469a-95cc-b1bdc890b8f4)

**Comment by georgjaehnig** [comment]
Fixed with https://github.com/trovu/trovu/commit/4ceee5d708dfda2c0ad12acee94f1d7891108202
