### ISSUE TITLE
[Enhancement] During build, or on reload, integrate a default config.yml 

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#336]
As partially mentioned here https://github.com/trovu/trovu/issues/332#issuecomment-2016413356 , I suggest this improvement to `trovu`:

`trovu`  should look for a local `config.yml` 

- during build time: in this case, a non web-accessible `config.yml` would be possible ; or
- on reload action: then a web-accessible `config.yml` has to be used ; or
- both possbilities, where the web-accessible `config.yml`  takes precedence over the built-in `config.yml`

and, of course, 

- a request-URI user-supplied `configUrl=config.yml` overrules any of the previous (if present).

**Comment by georgjaehnig** [comment]
Done in #398.
