### ISSUE TITLE
Feature | Dockerfile and Makefile to install & run project with 1 command

### ISSUE THREAD

**Issue by MindfulPol** [trovu/trovu#356]
I created a Dockerfile & Makefile to run the project and avoid installing node on my machine, it may be useful to have, great to be able to setup your project with 1 command.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it means? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #356</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @MindfulPol</code> (replace <code>20</code> with the amount, and <code>@MindfulPol</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by MindfulPol** [comment]
https://github.com/trovu/trovu/pull/355

**Comment by georgjaehnig** [comment]
Closed with #355.
