### ISSUE TITLE
Integration in Firefox (Desktop; 127.0 (64-bit)) no longer works

### ISSUE THREAD

**Issue by arne-cl** [trovu/trovu#389]
Dear Georg,

I was following the instructions from https://github.com/trovu/trovu/blob/master/docs/users/integration.md .
After clicking `Add "Trovu"`, I get the following error message:

![image](https://github.com/trovu/trovu/assets/994109/9badd8c3-b380-4a55-a3cf-920a5e4e95cc)
`Invalid format. Firefox could not install the search engine from https://trovu.net/opensearch/?`

I'm running a fresh install of Linux Mint 21.3 with Firefox installed from the distro's repo.
I will check if the error also occurs when I install Firefox from Mozilla's repo.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #389</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @arne-cl</code> (replace <code>20</code> with the amount, and <code>@arne-cl</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by arne-cl** [comment]
The error also occurs on Firefox 128.0b4 (64-bit) installed from Mozilla's repo. Here, the error message is `Invalid Format. Firefox could not install the search engine from: https://trovu.net/opensearch/?country=us&language=en`.

**Comment by georgjaehnig** [comment]
Thanks! There was a regression introduced in the creation of the opensearch XML (The file `https://trovu.net/opensearch/?country=us&language=en` started with a PHP error message.)

Should be fixed now, if not please reopen.
