### ISSUE TITLE
Shortcuts do not build on Mac

### ISSUE THREAD

**Issue by jessek** [trovu/trovu#394]
When attempting to build the code on my Mac, the shortcuts do not compile. The server runs, but no shortcuts are loaded. Screenshot of server running with nothing loaded:
<img width="1110" alt="Screenshot 2024-06-26 at 9 05 19 AM" src="https://github.com/trovu/trovu/assets/1842175/fba06ef6-5b0d-4eaa-8d24-de330ee22d82">

I've installed npm and node using Homebrew, https://brew.sh/

% npm --version
10.8.1
% node --version
v22.3.0

% git clone https://github.com/trovu/trovu.git

% npm ci

% npm run build > ~/output.txt 2>&1

Output of the build command:

<pre>

> trovu-web@1.0.0 build
> rollup --config --environment INCLUDE_DEPS,BUILD:production

loaded rollup.config.js with warnings
(!) Unused external imports
default imported from external module '@rollup/plugin-json' but never used

src/js/index.js → dist/public/...
created dist/public/ in 1s

src/js/process.js → dist/public/...
[1m[32mdist/public/style.css[0m 191 kB

> trovu-web@1.0.0 compile-data
> node -r esm src/js/cli.js compile-data --output ./dist/public/data.json

/Users/jessek/tmp/trovu/node_modules/esm/esm.js:1

[Massive blob of code]

TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at node:internal/main/run_main_module:30:49

Node.js v22.3.0
created dist/public/ in 589ms
</pre>

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #394</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @jessek</code> (replace <code>20</code> with the amount, and <code>@jessek</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by georgjaehnig** [comment]
Thanks for reporting this.

I checked and I use
``` 
node --version
v21.3.0
```
I can confirm your bug with Node version 22.3.0

So I suggest you install Node 21.3. [Here's how](https://chatgpt.com/share/ef365047-6653-48de-85b1-f7a4565ebfac).

I've also updated the [docs to mention Node 21.3](https://trovu.net/docs/developers/).

**Comment by jessek** [comment]
I have confirmed this method works for me. Thank you for the fast response!
