### ISSUE TITLE
No suggestions or submit work on Chrome/Brave for Android

### ISSUE THREAD

**Issue by georgjaehnig** [trovu/trovu#410]
When opening www.trovu.net on Chrome or Brave for Android, no suggestions or submit work. Seems as JS stopped running.

Reloading https://trovu.net/index.js / https://trovu.net/process.js does not help.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #410</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @georgjaehnig</code> (replace <code>20</code> with the amount, and <code>@georgjaehnig</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by erik55** [comment]
On my Fedora Linux computers and on my Android phones in Firefox trovu stopped working. That means I only see a white screen with a small *Loading* in the upper left corner. Forever. 

On the computer the solution was to press ctrl+shift+r when I saw that *Loading* thing. But on Firefox in Android I have no solution.

**Comment by georgjaehnig** [comment]
Opening trovu.net in Inkognito window (of Chrome for Android) made it work again (in Inkognito). Can you try that, too?

**Comment by georgjaehnig** [comment]
To make it work in non-Inkognito, too, one can [delete the browser cache](https://stackoverflow.com/a/25573613) – just confirmed this myself.

Looking for a less harsh method.

But then it seems it is in fact a caching issue.

Still puzzled why it got deployed, as the original issue was only about the settings icon.

**Comment by georgjaehnig** [comment]
I think I got it: Open https://trovu.net/data.json on the affected browser, maybe even with a reload (swipe down once it's opened).

The new JS code looks for a "config" field in there which the older version of `data.json` did not have, causing the JS to stop running.

So it's also a cache-busting problem, just a different one. 

Let me know if it worked for you, too.

**Comment by georgjaehnig** [comment]
@erik55 I'm working on a caching fix atm.

Can you tell if you know about more people  affected by this glitch, others than yourself? I want to estimate how big this one issue was. And I got no other reports, also not in the core users' Telegram group.

**Comment by erik55** [comment]
As far as I know all my friends and family (all that use the Firefox browser). Have sent them the fix with the link to `data.json`

**Comment by georgjaehnig** [comment]
OK, to be safe, I deployed a new version that should also stop the bug (make a new call to `data.json` automatically, with some cache busting added again).

Thanks again for reporting. And feel free to reach out in the future even earlier, I'm reading the issues here constantly. There's also a Telegram group @trovu_net
