### ISSUE TITLE
How to start server with TLS?

### ISSUE THREAD

**Issue by jessek** [trovu/trovu#413]
I'd like to set up TLS for my local installation. I know the underlying http-server has TLS options, and certainly there is TLS enabled on the public trovu.net site. How can I use certificates to enable TLS on my local instance?

FWIW, I found and <3 the Github workflow, but it doesn't mention TLS.

https://github.com/trovu/trovu/blob/master/.github/workflows/deploy.yml

thanks!
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #413</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @jessek</code> (replace <code>20</code> with the amount, and <code>@jessek</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by georgjaehnig** [comment]
Thanks for your question. So on my www.trovu.net, I do not use `npm run serve` but simply the built-in Apache 2.4.

This then uses `certbot` to get certificates from https://letsencrypt.org/

 Does this help you?

Edit: In other words, you don't need the built-in `http-server` (started with `npm run serve`). You just need to host the built static HTM/JS/CSS files.

**Comment by jessek** [comment]
It is helpful, yes. I'm glad you confirmed there is no way to do it with `npm run serve`

But i'd <3 to understand how you connect the service to the Apache web server.

**Comment by georgjaehnig** [comment]
> But i'd <3 to understand how you connect the service to the Apache web server.

Pretty straight-forward, just using the default config, with the [http2](https://httpd.apache.org/docs/2.4/mod/mod_http2.html) and [ssl](https://httpd.apache.org/docs/current/mod/mod_ssl.html) modules.

Oh, and I just see: There's a tiny bit of code using PHP but it's not crucial for the core to work:

https://trovu.net/opensearch/index.php is used to create the [Opensearch XML](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) code. It's needed when users want to [install Trovu in their browser as a (default) search engine](https://trovu.net/docs/users/integration/). But you can get away without it if your users add your local Trovu to the browser [by directly entering the search URL](https://trovu.net/docs/users/integration/#other).

I'm also willing to replace this piece of PHP with some better alternative. Just didn't know any better so far.

**Comment by jessek** [comment]
This is perfect. Thank you for sharing the configuration information; very helpful and much appreciated.
