### ISSUE TITLE
trovu.net: Country is DE but incorrectly detected as US

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#429]
https://trovu.net/#country=us&language=de

When I start trovu.net in my Firefox (DE-DE), the country is incorrectly set to US, whereas my IP is currently correctly detected as DE.

May be a regression?
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #429</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @Wikinaut</code> (replace <code>20</code> with the amount, and <code>@Wikinaut</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by georgjaehnig** [comment]
Cannot confirm. I've

- set my Firefox preferred language to de-AT
- call https://trovu.net/
- and get German and Austria, with a redirect to https://trovu.net/#country=at&language=de

as intended.

There is not IP detection anymore as there was in FindFind.it. Language and country are getting derived from the browser's preferred language setting

If there is no country specified, e.g. `de` and not `de-AT`, then the country is picked from the default country setting.
