### ISSUE TITLE
The defaultKeyword is not respected when entering "not-a-keyword something" (which should result in action "defaultKeyword not-a-keyword something") → . Trying with non-reachable.

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#430]
I noticed, that I receive an error message, when no keyword is detected, but the default keyword is apparently also disregraded

My `trovu.config.yml` is
```
namespaces:
- o
- de
- .de
- shortcuts
defaultKeyword: s
language: de
country: de
```

The wanted "s" (default keyword) is not triggered, when I search for something "not-a-keyword something".

**Comment by Wikinaut** [comment]
To clarify:


When I enter "not-a-keyword", then defaultKeyword is working an searches (in my case) "s not-a-keyword".

What I report here is that I expect this working for all cases, also such as "not-a-keyword something".

Then I expect trovu to execute "s not-a-keyword something". It looks, that this is a functionality, which has not yet been implemented.

**Comment by Wikinaut** [comment]
On one computer, it is however correctly working like expected (here with user-defined config.yml):

```
Loading https://startpage.com/do/search?q=not-a-key-word%20something

Success fetching via default /data.json?5e6202c
Success fetching via default /config.yml
No shortcut found for not-a-key-word 1 yet. Trying with the whole argument string as the only argument.
No shortcut found for not-a-key-word 1 yet. Trying with default keyword.
Used template: https://startpage.com/do/search?q=<query>
Redirect to:   https://startpage.com/do/search?q=not-a-key-word%20something
```

**Comment by Wikinaut** [comment]
puh. invalid.

The problem appears to stem from an invalid (outdated) shortcut in o.yml for `startpage`.

The correct url value for shortcut `s`needs to be `https://www.startpage.com/sp/search?query=<query>`.

**Comment by Wikinaut** [comment]
On another computer it did not work again, therefore reopening.


Debug says:


```
Loading 

Success fetching via default /data.json?5e6202c
No shortcut found for hggh 1 yet. Trying with the whole argument string as the only argument.
No shortcut found for hggh 1 yet. Trying with non-reachable.
Redirect to:   ../index.html#country=de&debug=1&language=de&query=debug%3Ahggh+hghg+hg&status=not_found
```

**Comment by Wikinaut** [comment]
I close the issue, it is now superseded by #433

**Comment by Wikinaut** [comment]
I need to reopen this issue, as the problem is still present.

**Comment by georgjaehnig** [comment]
I just tried to reproduce this. First with `defaultKeyword` in the URL:

https://trovu.net/?#country=us&defaultKeyword=g&language=en

Calling a query `foobar` redirects to Google, as expected.

Then via https://trovu.net/?#github=georgjaehnig [where I've set a default keyword](https://github.com/georgjaehnig/trovu-data-user/blob/master/config.yml).

Works for me, too.

So how exactly are you setting `defaultKeyword` on your side?

**Comment by Wikinaut** [comment]
It is in trovu.config.yml and, by the way, also in config.yml - as written in the start post of this issue.

```
namespaces:
- o
- de
- .de
- shortcuts
defaultKeyword: s
language: de
country: de
```

So what I report is, that it appears not be respected in some cases on some browsers on some computers. At the moment, I have unfortunately nor an idea nor a hint what exactly influences the behaviour. It looks that it could be glitch in the trovu software stack, the behaviour is reproducible.

**Comment by georgjaehnig** [comment]
So as I said, `defaultKeyword:` is currently not supported in `trovu.config.yml`. The ticket for adding it there is #433.
