### ISSUE TITLE
Issue with #configUrl= or with trovu.config.yml - cannot force the browser to use the built-in

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#432]
I have big problems after having used #configUrl=/config.yml and then trying to move over to using the built-in trovu.config.yml.

I cannot "reset" or delete the configUrl to use effectively the built-in trovu.config.yml, it simply does not work.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #432</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @Wikinaut</code> (replace <code>20</code> with the amount, and <code>@Wikinaut</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by Wikinaut** [comment]
related to issue #430

**Comment by georgjaehnig** [comment]
Can you elaborate

- what you want to achieve,
- what you are then doing,
- and what are you getting (instead of what you expected)?

See also [my comment here](https://github.com/trovu/trovu/issues/433#issuecomment-2241793205), maybe that clears up the issue a bit.

**Comment by Wikinaut** [comment]
Ir works in browsers.
It does not work in PWA.

**Comment by georgjaehnig** [comment]
Yes, `configUrl` not yet working with the PWA. I'd need to add it to the Settings modal, as you can't manipulate the URL within a PWA.

Are you actually using the PWA? And would you actually use it with configUrl? 

Then we can remember this request in the ticket here and change it to a feature request.  Maybe also other users will add a 👍 as a sign that they need this.

There are plenty of things that can be done for Trovu, as you can see in the open tickets. I need to prioritize what comes first. Implementing something merely for consistency, without users actually needing it, is not what I want to do, as it would be very ineffective.

**Comment by Wikinaut** [comment]
I use trovu on all of my devices, as PWA and in the browser (FF). Many devices, in total > 5.

**Comment by georgjaehnig** [comment]
Now  that `defaultKeyword` can be set in the `trovu.config.yml` (#433), is there still a usecase for you to need `configUrl` in the PWA?

Asking for prioritization.

**Comment by Wikinaut** [comment]
Hmm, shouldn't trovu behave the same way regardless how it is used/installed? This is my view.

Do you want me to test as PWA (I stopped that use meanwhile because of the problems I encountered when `defaultKeyword` was not working everywhere)

I will check the PWA working or not and report back here.

**Comment by Wikinaut** [comment]
Result: I got it working (PWA, stored on the homescreen with explicit configUrl=.... and with defaultKeyword in `configUrl` and in `trovu.config.yml`) PWA appears to work.

I am closing this issue now as this appears to be working now.
