### ISSUE TITLE
Allow to set `defaultKeyword` also in `trovu.config.yml`

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#433]
My `trovu.config.yml` is:

```
namespaces:
- o
- de
- .de
- shortcuts
defaultKeyword: s
language: de
country: de
```

When entering `hggh hghg hg` it does not fire defaultKeyword "s" (startpage), see debug log:

```
Loading 

Success fetching via default /data.json?5e6202c
No shortcut found for hggh 1 yet. Trying with the whole argument string as the only argument.
No shortcut found for hggh 1 yet. Trying with non-reachable.
Redirect to:   ../index.html#country=de&debug=1&language=de&query=debug%3Ahggh+hghg+hg&status=not_found
```

See #430
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #433</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @Wikinaut</code> (replace <code>20</code> with the amount, and <code>@Wikinaut</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by georgjaehnig** [comment]
`trovu.config.yml` does not accept a `defaultKeyword`. It's the (default) configuration for a Trovu instance, not for a user.

**Comment by Wikinaut** [comment]
Please elaborate, why you think it is necessary to disallow this keyword as default for the instance.

In my view it is a bug, if defaultKeyword is allowed in config.yml for users but not having [the option] to set it up a global default.

In my case, as mentioned in #430, the default did not even work in certain constellations - which might point to another, currently unknown bug - so it would be a clever solution to allow defaultKeyword.

See also your documentation regarding defaultKeyword: there is no restriction mentioned, not to use it in trovu.config.yml.

**Comment by georgjaehnig** [comment]
> Please elaborate, why you think it is necessary to disallow this keyword as default for the instance.

It's not deliberately disallowed, but simply not implemented.

`trovu.config.yml` is for configuring the instance. We could in fact think about allowing to set a `defaultKeyword` in there, but then the question would arise how `language` and `country` shall be interpreted: Should they still be overridden by the browser's preferred language (as it happens now)?

I'm not saying it shouldn't be implemented. I'm saying it would be a new topic, a new feature that'd require some planning.

You can present me a use case where you think setting a defaultKeyword for the whole instance would be a good think to do.

**Comment by Wikinaut** [comment]
> You can present me a use case where you think setting a defaultKeyword for the whole instance would be a good think to do.


Use case:

I run my instance for ny friends & family, as replacement for my own former search assistant tool. For this group, I manage all the bookmarks and default settings and it is almost mandatory to have the same functionality as before, whith my older search assistant.  In this tool, it was google and later in time it became startpage, which was then hard-coded.

**Comment by Wikinaut** [comment]
Thus I kindly ask to implement a way to have the value of the option `defaultKeyword` as an (optional) default setting for the instance.

**Comment by Wikinaut** [comment]
I am using a workaround on my instance, so that in any case my config.yml is used as a default, wherein the `defaultKeyword=s` is present.

However, as mentioned above, this functionality should be part of the default trovu.config.yml

Apache2 config:

```
RewriteEngine on
RewriteCond %{REQUEST_URI} !index.html#configUrl
RewriteRule ^/$ /index.html#configUrl=/config.yml [NE,R=301]
```

**Comment by georgjaehnig** [comment]
OK, I've made this an enhancement ticket.

I'll still need to figure out how `language:/country` shall be interpreted then. We will probably need to rename the settings in `trovu.config[.default].yml` to
```yaml
default:
  namespaces: 
  - o
  - <$language>
  - .<$country>
  language: en
  country: us
  # defaultKeyword: g
```
to make sure that they can be overridden. Especially for `language` and `country` it has to be clear, that the browser will override them.

To stop the browser from overriding them, and always use this language/country, we could then have
```yaml
language: en
country: us
```
I'll still need to think about what's best here.

**Comment by Wikinaut** [comment]
Yes, this sounds reasonable.

**Comment by Wikinaut** [comment]
The defaultKeyword is - for me - the more important issue to be fixed compared to the language/country setting issue.

**Comment by georgjaehnig** [comment]
@Wikinaut Should work now.
