### ISSUE TITLE
Browser Extension / Making Trovu faster

### ISSUE THREAD

**Issue by Gregoor** [trovu/trovu#453]
Heya,

super neat project! Found this through the Berlin ACX Telegram group and was very happy to find it, I've had all kinds of similar site search shortcuts set up in my browser but was also looking for a more portable, mobile-friendly version.

The only thing that irks me about this is that searching is less instant, because of the hop through trovu.net. Has anyone already done the work of pouring this code here into a browser extension to skip the middle man?
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #453</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @Gregoor</code> (replace <code>20</code> with the amount, and <code>@Gregoor</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by georgjaehnig** [comment]
Hi @Gregoor, happy you found Trovu and like it!

It's true there is no browser extension – but there are ways to integrate Trovu seamlessly into your browser. Mostly by the standardized OpenSearch protocol – just have a look [in the docs](https://trovu.net/docs/users/integration/).

Let me know if that helps or if you have more questions!

**Comment by Gregoor** [comment]
In terms of integration I'm pretty happy with the seamlessness, my only issue is speed, i.e. googling does not feel as instant anymore. And I imagine with the hop through another site it would always feel this way, and only a browser extension could solve for that.

Now knowing that it does not exist yet, I'll spend my next side-project time on prototyping sth based on your code and will report back, if that's wanted

**Comment by georgjaehnig** [comment]
> And I imagine with the hop through another site it would always feel this way, and only a browser extension could solve for that.

A direct call of integrated Trovu calls `https://trovu.net/process/` which itself calls `https://trovu.net/data.json`. But both files are cached in your browser. So technically, it should make no difference to a browser extension.

I know about the "perception" of "not instant", yet I think it's because during the browser still shows `https://trovu.net/process/`, it already loads the target site (e.g. Google) in the background. Calling Google directly only shows you a blank screen but the time is eventually the same. (Yet I'm open to see counter-evidence, e.g. if one would measure both ways of calling Google.) 

Still, I did already think about creating a browser extensions also for promotion reasons (being visible in the addon/extension stores). If you already have experience with that I'm happy if you could help! It could be part of this monorepo.

I heard there already exists a [unified API for many browsers](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension).

**Comment by Gregoor** [comment]
I agree that the flash of text probably does something wrt perception, but I lean towards there being more to it.

While I haven't done a side-by-side yet, looking at network timing in devtools for a random query, I see the request to google being queued (400ms) after hitting Enter (with cache). My vague UX delay being perceptible minimum is 100ms, so we are over that.

But now looking at all the resources coming in from-cache instantly, I'm wondering where those 400ms go, maybe it'd be more interesting for me to look at script execution times first. I guess I atm don't see a reason why it shouldn't be sub-100ms.

**Update#1**
In local dev I can also see the 400ms, but I can only account for 160ms of those within the JS. On the upside I think most of those 160ms will go away once one caches the result of `env.populate`, but I might be missing some intricacies here.
I'm also confused wrt where the remaining 240ms are spent.

**Update#2**
Just to sanity-check myself I've added a simple page that only `location.replace()`s the current page with a google search for a given hash, which still gives me 150ms of delay until the first request to Google is queued. So that's my new baseline. Only then I realized my installed extensions might also have an impact (full circle much), and indeed, without them, in private browsing, Google is only delayed by 50ms.
So I went and also tried trovu in private browsing and indeed, only 160ms delay, just ever so slightly above noticeable.

So here are the numbers as I currently understand them:

|          | w/exts | w/o   |
|----------|--------|-------|
| baseline | 150ms  | 50ms  |
| trovu    | 400ms  | 160ms |
| diff | 350ms | 110ms |

So 110ms might be up for grabs if there's something to optimize in the code. But then there is 3 times that between running it w/ and w/o extensions. All those numbers are from a Macbook Air (M3), so there could be an even more noticeable multiplier for these on older machines.

I think I've reached an ironic conclusion for now: a web extension might still be worth it (for me), because it gets to skip other web extensions adding intercep/initialize costs to opening the trovu page. Ha!

**Update#3**
I would've probably looked at the [omnibox API](https://developer.chrome.com/docs/extensions/reference/api/omnibox#event-onInputEntered) as the extension point, but then realized the hipster-browser I'm using (Arc) can't be extended that way, despite being a Chromium. So I'll probably not pursue this path anymore, until that changes (or I switch browsers). I hope my notes will be useful to someone nonetheless.

**Comment by georgjaehnig** [comment]
Just wanna say that I'm happy you're looking into this!

**Comment by Gregoor** [comment]
As mentioned in the third update, I won't pursue the extension for now. That said, I did a [hacky very-much-incomplete 50-line implementation](https://github.com/Gregoor/trovu/blob/experiment/ou/src/main.ts) of trovu that goes HARD on localStorage to cut down on initialization costs. With that I reach around 260ms w/exts, which feels good enough for me, for now. It's hosted on gh pages as well: https://gregoor.github.io/trovu#query=%s

**Comment by georgjaehnig** [comment]
Hi @Gregoor, I'm happy you find a way to use it to your needs!

As you write, your implementation is not fully complete, as for instance it lacks dealing with [typed arguments](https://trovu.net/docs/shortcuts/url/#argument-types) or with [includes](https://trovu.net/docs/shortcuts/include/).

But if you don't need that, then great that you've found a way to accelerate it!
