### ISSUE TITLE
"Add to Firefox" broken

### ISSUE THREAD

**Issue by texttheater** [trovu/trovu#49]
Trovu's "Click to add to Firefox" button no longer works as of Firefox 78/79 because [`window.external.AddSearchProvider` was deprecated and is now a dummy function](https://bugzilla.mozilla.org/show_bug.cgi?id=1632447).

There's probably no easy solution, cf. #11 

My current workaround is to use the [Add custom search](https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/) add-on.

**Comment by georgjaehnig** [comment]
Thanks for the hint! I have solved it now via a pure OpenSearch approach: In Chrome and Firefox, the OpenSearch description should be auto-discovered. Please follow the instructions under *Add to browser*.

Does it work for you?

**Comment by texttheater** [comment]
It does, great, thank you very much!

**Comment by georgjaehnig** [comment]
Thanks for quick feedback!
