### ISSUE TITLE
OpenSearch description ignores, overwrites user's configured country and language

### ISSUE THREAD

**Issue by texttheater** [trovu/trovu#51]
### Steps to reproduce

1. Go to https://trovu.net/opensearch/?github=texttheater

### Expected behavior

The `Url`, `UpdateUrl` and `SearchForm` URL in the description have no `language` and `country` parameters, or match the values configured by the user in https://github.com/texttheater/trovu-data-user/blob/master/config.yml (`de` and `de` in this case).

### Actual behavior

All three URLs contain `language=en&country=us`, meaning that if the user uses OpenSearch to add their personalized Trovu to the browser, their country and language will have no effect.

**Comment by georgjaehnig** [comment]
Thanks for reporting. 1887f0270709b58c6c510e146967405f817c51cb should have fixed it. (Only using the `github=` parameter when it is set.)

**Comment by texttheater** [comment]
Thans for the quick fix!
